### ISSUE TITLE
Understand Comma

### ISSUE THREAD

**Issue by asarfraaz** [ishabalu/pythonpgms#1]
What would happen if I replace "," in this line with "+" ?

https://github.com/ishabalu/pythonpgms/blob/6a2129a06418e1d339bd2ef48ce53203fe6ea9ac/pgm1.py#L2

Can you guess the difference between "," and "+", based on what you see in the output ?

**Comment by ishabalu** [comment]
"+" is concatenating the string "," is creating spaces
